//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visus.VcpkgCache.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visus.VcpkgCache.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be an existing directory where packages can be stored..
        /// </summary>
        public static string ErrorInvalidCachePath {
            get {
                return ResourceManager.GetString("ErrorInvalidCachePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified authentication token is invalid..
        /// </summary>
        public static string ErrorInvalidToken {
            get {
                return ResourceManager.GetString("ErrorInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication header &quot;{0}&quot; is missing..
        /// </summary>
        public static string ErrorMissingHeader {
            get {
                return ResourceManager.GetString("ErrorMissingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid authentication token was specified in the options..
        /// </summary>
        public static string ErrorMissingToken {
            get {
                return ResourceManager.GetString("ErrorMissingToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content of the package must be provided..
        /// </summary>
        public static string ErrorPackageContent {
            get {
                return ResourceManager.GetString("ErrorPackageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified package name is invalid..
        /// </summary>
        public static string ErrorPackageName {
            get {
                return ResourceManager.GetString("ErrorPackageName", resourceCulture);
            }
        }
    }
}
